### ISSUE TITLE
Vanilla Support

### ISSUE THREAD

**Issue by Hojosa** [John-Smith-Modded/JSTR-Vanilla-1.12.x#1]
Why is there still a Vanilla repo?
Asking because, it would make more sense to require the Vanilla pack from https://www.johnsmithlegacy.co.uk/, and load the JSTR afterwords(including the JSTR Vanilla overrides)

**Comment by lesdmark** [comment]
There is still a vanilla repo because there are differences between Jim Stone's version and the Repo we maintain. I personally would not want to have to add 2 packs just to get to the same place as one unified pack. We are not just a mod textures pack.

**Comment by Hojosa** [comment]
Makes sense, thanks for the answer.
