### ISSUE TITLE
Redstone Torch texture issue

### ISSUE THREAD

**Issue by Shandoo94** [John-Smith-Modded/JSTR-Vanilla-1.12.x#4]
Version MC1.12.x-v1.2.0a
Forge: 14.23.5.2838

![2019-07-19_19 17 34](https://user-images.githubusercontent.com/21018028/61553621-17d39980-aa5b-11e9-91d6-4e162ee9f6a5.png)

**Comment by Shandoo94** [comment]
sorry wrong repo

**Comment by lesdmark** [comment]
No you were commenting in the correct repo, This issue has now been resolved. Any Vanilla 1.12 JSTR textures are in this repository not the modded one. I will push a new release on the JSTR modded repo which includes this as soon as I get a chance.

**Comment by lesdmark** [comment]
Here is a [link](https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases/download/MC1.12.x-v1.2.5/JSTR.1.12.x.zip) to the most up to date version of the pack on GitHub.
